### ISSUE TITLE
SASS files without rules generate `undefined` in their .cljc files

### ISSUE THREAD

**Issue by acron0** [WorksHub/cljc-css-loader#1]
Currently, any SASS files that don't directly include a rule (for example, files with only `import` statements) generate invalid `.cljc` files, as they include the word `undefined` beneath the namespace declaration.

**Steps to reproduce**
- Clone the project 
- `cd cljc-css-loader/example`
- `cat /dev/null >| styles/main.sass` (bash; removes content from `main.sass`)
- `npx webpack`
- `cat cljc/styles/main.cljc`

**Expected outcome**
- `main.cljc` is a valid CLJC file and contains only the namespace declaration
OR
- `main.cljc` is not generated at all

**Actual outcome**
- `main.cljc` is not a valid CLJC file
```bash
(ns styles.main)
undefined
```

**Comment by taditdash** [comment]
Hi @acron0,

I cloned and executed the steps you mentioned. Here is the screenshot.

<img width="880" alt="Screenshot 2021-04-11 at 7 36 58 PM" src="https://user-images.githubusercontent.com/11786875/114307444-4a5dd980-9afd-11eb-8989-c7d0a5386c29.png">

I see the following output instead of undefined as you said.
<img width="364" alt="Screenshot 2021-04-11 at 7 37 49 PM" src="https://user-images.githubusercontent.com/11786875/114307474-695c6b80-9afd-11eb-8704-89d5a8b01251.png">

Am I missing anything?

Thanks,
Tadit

**Comment by acron0** [comment]
@taditdash I think you missed the step where I blanked the `main.sass` file.
